### ISSUE TITLE
Registration Views Sub-Module is breaking my site

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/registration#28]
When I enable the registeration Views sub-module I'm getting the following error and it's completely breaking my site, preventing me from disabling the module. 

This happened on an existing dev site and a fresh install of Backdrop CMS. 

`Fatal error: Uncaught Error: Class 'RegistrationViewsController' not found in /app/modules/entity_plus/views/entity_plus.views.inc:30 Stack trace: #0 /app/core/includes/module.inc(975): entity_plus_views_data() #1 /app/core/modules/views/includes/cache.inc(90): module_invoke_all('views_data') #2 /app/core/modules/views/includes/cache.inc(75): _views_fetch_data_build() #3 /app/core/modules/views/views.module(1141): _views_fetch_data(NULL, true, false) #4 /app/modules/entity_plus/views/entity_plus.views.inc(320): views_fetch_data() #5 /app/core/modules/views/includes/utility.inc(456): entity_plus_views_plugins() #6 /app/core/modules/views/includes/cache.inc(148): views_discover_plugins() #7 /app/core/modules/views/views.module(1152): _views_fetch_plugin_data(NULL, NULL, false) #8 /app/core/modules/views/views.module(114): views_fetch_plugin_data() #9 /app/core/includes/theme.inc(545): views_theme(Array, 'module', 'views', 'core/modules/vi...') #10 /app/core/includes/theme.inc(701): _theme_process_registry(Array, 'views', 'm in /app/modules/entity_plus/views/entity_plus.views.inc on line 30`

NOTE: I tried with both the official release and the dev versions of the module. I hope to do more testing soon and report back.

**Comment by stpaultim** [comment]
I confirmed this problem again - and it's pretty serious, because it has the potential to break existing sites and make it very difficult for a user to regain control of their site if they are not an experienced developer. 

Steps to recreate:

1) Spin up a sandbox site on Backdropcms.org
2) Add / Enable the Registration module, including Entity, Entity Plus, and Entity UI (no problems)
3) Enable Registration Entity Access (no problems)
4) Enable Registration Views and get major PHP error

`Fatal error: Uncaught Error: Class 'RegistrationViewsController' not found in /var/lib/tugboat/backdrop/modules/entity_plus/views/entity_plus.views.inc:30 Stack trace: #0 /var/lib/tugboat/backdrop/core/includes/module.inc(975): entity_plus_views_data() #1 /var/lib/tugboat/backdrop/core/modules/views/includes/cache.inc(90): module_invoke_all('views_data') #2 /var/lib/tugboat/backdrop/core/modules/views/includes/cache.inc(75): _views_fetch_data_build() #3 /var/lib/tugboat/backdrop/core/modules/views/views.module(1141): _views_fetch_data(NULL, true, false) #4 /var/lib/tugboat/backdrop/modules/entity_plus/views/entity_plus.views.inc(320): views_fetch_data() #5 /var/lib/tugboat/backdrop/core/modules/views/includes/utility.inc(456): entity_plus_views_plugins() #6 /var/lib/tugboat/backdrop/core/modules/views/includes/cache.inc(148): views_discover_plugins() #7 /var/lib/tugboat/backdrop/core/modules/views/views.module(1152): _views_fetch_plugin_data(NULL, NULL, false) #8 /var/lib/tugboat/backdrop/core/modules/views/views.module(1 in /var/lib/tugboat/backdrop/modules/entity_plus/views/entity_plus.views.inc on line 30`

At this point the site is unusable and I'm no longer able to disable the module to recover the site.

**Comment by jenlampton** [comment]
I was able to fix my site by commenting out line 177 of registration_views.module:
```php
//$entity_info['registration']['views controller class'] = 'RegistrationViewsController';
```

~It looks like this class is missing. It's in the D7 version, so I think it should be easy to add back. PR coming soon.~ err, actually it looks like this has been partially rewritten. I don't have time to get into this right now, but maybe I'll have a look later.

**Comment by stpaultim** [comment]
@hosef or @docwilmot - I see some activity in the issue queue today and want to make sure that someone has seen this issue. If there is any chance of a new release for this module soon, I think it very important that this problem is addressed, because it breaks sites in a way that is difficult to recover from. 

I had to manually disable the module directly in the database to recover access to my site. Many users will not be able to do that. If we can fix this, should we remove this submodule until we are able to fix it?

**Comment by hosef** [comment]
@stpaultim I believe this is the same issue as #23. I pushed a change to the 1.x-1.x branch today that fixes this issue. I am going to go through all of the PRs and if everything seems to be working after that I can tag a new release.

**Comment by stpaultim** [comment]
@hosef -Thanks for doing this.

I'll test the current dev release on my site. Fortunately, I still have the test site set up that I used  to create this issue.

**Comment by stpaultim** [comment]
@hosef - I did the following

1) Downloaded the zip file for 1.x-1.x
2) Replaced the existing Registration module 
3) The main registration module was already enabled, but I enabled the three sub-modules

I got this error:

```
Error
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'waitlist' for key 'name': INSERT INTO {registration_state} (`registration_state_id`, `status`, `module`, `name`, `label`, `description`, `default_state`, `active`, `held`, `show_on_form`, `weight`) VALUES (default, default, default, :db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7); Array ( [:db_insert_placeholder_0] => waitlist [:db_insert_placeholder_1] => Wait list [:db_insert_placeholder_2] => Special state for registrations after capacity is reached. [:db_insert_placeholder_3] => 0 [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => 0 [:db_insert_placeholder_6] => 1 [:db_insert_placeholder_7] => 0 )
```
Not sure if I would have the same problem on a clean site. Will test.

**Comment by stpaultim** [comment]
@hosef - Good news. I was able to do the following:

1) Hit the back button to module page and disable all 4 modules (3 sub-modules first)
2) Uninstall all 4 modules
3) Re-enable them one at a time without any major or fatal errors. 

I did get this in the log `Notice: Array to string conversion in _views_data_process_entity_types() (line 110 of /app/core/modules/views/includes/cache.inc).`, but I suspect that is a different issue.

**Comment by hosef** [comment]
@stpaultim I ran into that issue earlier as well. I think there is something not working correctly in the install files. I will take a look at that later.

**Comment by stpaultim** [comment]
@hosef To be clear, I did not test the functionality of the modules at all. I was only able to test the install process to make sure that they did not cause fatal errors during installation.

I have a meeting now and will try to test these modules later today. 

In theory, we could probably close this issue - but maybe I'll wait for a little more testing?

**Comment by stpaultim** [comment]
I did another test and I believe that THIS issue is resolved. 

I've opened a new issue for the new issue: https://github.com/backdrop-contrib/registration/issues/33
