### ISSUE TITLE
Notice: Array to string conversion in _views_data_process_entity_types()

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/registration#33]
In testing the fix for another issue, I am now finding this in my recent log messages. 

`Notice: Array to string conversion in _views_data_process_entity_types() (line 110 of /app/core/modules/views/includes/cache.inc).`

I don't know if this is necessary, but I'm opening this issue so that I can close the other issue which seems to be resolved. This one appears to be much less critical.

**Comment by hosef** [comment]
@stpaultim I commited a change that should fix this error.

**Comment by stpaultim** [comment]
@hosef - I just ran into this error again. I downloaded and tested the DEV branch and I am not getting the error.

**Comment by argiepiano** [comment]
This is still a problem in the current version of Registration. I guess the PR that was committed on January 28 2022 (last year) has not yet made it into a released version of the module? (latest release is January 20, 2022). 

This caused issues for someone as reported in the [Forum](https://forum.backdropcms.org/forum/views-exposed-forms-being-nuked-after-cache-clearing#comment-4908)

**Comment by laryn** [comment]
We have a new release, so I'm closing this issue.
